spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        hbm2ddl:
          auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect

riot:
  api:
    key: RGAPI-892a699c-e3e2-41c9-a6d8-c5cb377570f6

