spring:
  config:
    activate:
      on-profile: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(oo5MCILs3RnV8TrEhd3BKGVygGE0fTToJF3rIGUHpGXRKozZ0PWKqB8bxFtRxDsCPBGoAHCjTxI5l5q2DTQsrDq6p5Dk6okqYG1NJYQE2yvfGA5k4xsJPw==)
            client-secret: ENC(FztXVwaQl+f0Xh0GNoBslpgyESpv8lhC5NhZ41fLuFJHMHZEc5TLf0cHhTSc5jP8)
            scope:
              - profile
              - email