spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        hbm2ddl:
          auto: update
    open-in-view: false

riot:
  api:
    key: RGAPI-883e69c1-ee63-467d-8f3f-41852244cc0f

